- name: CWTools Action
  uses: cwtools/cwtools-action@v1.0.0
on: [pull_request, push]
jobs:
  cwtools_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 # required
    - uses: cwtools/cwtools-action@v1.1.0
      with:
        game: hoi4
        locLanguages: "english"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required, secret is automatically set by github
        
        
